name: fastotv_common
author: Alexandr Topilski <support@fastogt.com>
description: Flutter FastoGT common files
version: 1.1.0

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  screen: ^0.0.5
  ntp: ^1.0.7
  intl: ^0.16.1
  flutter_material_color_picker: ^1.0.5
  device_info: ^0.4.2
  package_info: ^0.4.3
  fastotv_device_info:
    git:
      url: https://github.com/fastogt/fastotv_device_info.git
      ref: master
  volume:
    git:
      url: https://github.com/fastogt/Volume_Flutter.git
      ref: master
