name: fastotv_common
author: Alexandr Topilski <support@fastogt.com>
description:
version: 1.0.0

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  crypto:
  archive:
  dart_chromecast: ^0.1.2
  cached_network_image: ^2.0.0-rc
  screen: ^0.0.5
  intl: ^0.16.0
  flutter_material_color_picker: ^1.0.5
  device_info: ^0.4.1+4
  fastotv_device_info:
    git:
      url: https://github.com/fastogt/fastotv_device_info.git
      ref: master
  video_player:
    git:
      url: https://github.com/fastogt/video_player.git
      ref: master
  flutter_mdns_plugin:
    git:
      url: https://github.com/terrabythia/flutter_mdns_plugin.git
      ref: master
  volume:
    git:
      url: https://github.com/fastogt/Volume_Flutter.git
      ref: master
  fastotv_dart:
    git:
      url: https://github.com/fastogt/fastotv_dart.git
      ref: master
  persist_theme:
    git:
      url: git://github.com/fastogt/plugins.git
      ref: master
      path: packages/persist_theme

dev_dependencies:
  test: ^1.3.0