name: flutter_common
author: Alexandr Topilski <support@fastogt.com>
description: Flutter FastoGT common files
version: 1.1.1

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  screen: ^0.0.5
  ntp: ^1.0.7
  intl: 0.16.1
  flutter_material_color_picker: ^1.0.5
  responsive_builder: ^0.3.0
  device_info: ^1.0.0
  url_launcher: ^5.7.2
  package_info_plus: ^0.6.2
  fastotv_device_info:
    git:
      url: https://github.com/fastogt/fastotv_device_info.git
      ref: master
  volume:
    git:
      url: https://github.com/fastogt/Volume_Flutter.git
      ref: master

dev_dependencies:
  dart_rules:
    git:
      url: https://github.com/fastogt/dart_rules.git
      ref: main
