name: flutter_common
author: Alexandr Topilski <support@fastogt.com>
description:
version: 1.0.0

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  crypto:
  archive:
  dart_chromecast: ^0.1.2
  flutter_mdns_plugin:
    git:
      url: https://github.com/terrabythia/flutter_mdns_plugin.git
      ref: master
  volume:
    git:
      url: https://github.com/fastogt/Volume_Flutter.git
      ref: master

dev_dependencies:
  test: ^1.3.0